### ISSUE TITLE
ENH: Add 'postgis' platform ... as alias for Postgres docker with PostGIS extension

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-config#12]
So we can do:
```yml
ebean:
  dbSchema: mygisapp

  test:
    platform: postgis
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: mygisapp
```

So `postgis` plaform is effectively an alias for ...

```yml
ebean:
  dbSchema: mygisapp

  test:
    platform: postgres
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: mygisapp

    postgres:
      containerName: postgis
      image: mdillon/postgis
      extensions: postgis
      url: jdbc:postgresql_lwgis://localhost:7432/mygisapp
      driver: org.postgis.DriverWrapperLW
```
