### ISSUE TITLE
Add support for automatically configuring the DataSource for an extraDB (Postgres only at the moment)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-config#16]
This means we can specify:

```yml
ebean:
  test:    
    platform: postgres # h2, postgres, mysql, oracle, sqlserver, sqlite
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: main

    ## Extra separate database ...
    extraDb: extra
    extraDbInitSqlFile: init-extra-database.sql
```

And don't need to explicitly specify:

```yml
datasource:
  central:
    username: extra
    password: test
    url: jdbc:postgresql://localhost:6432/extra
    driver: org.postgresql.Driver
```
