### ISSUE TITLE
Support fastStartMode option

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-config#18]
Refer - https://github.com/ebean-orm/ebean-test-docker/issues/28

```yml
ebean:
  test:
    platform: postgres # h2, postgres, mysql, oracle, sqlserver, sqlite
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: my_app
    fastStartMode: true
```
