### ISSUE TITLE
ENH: Add ebean.test.localDevelopment to make marker file explicit and configurable

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-config#27]
The marker file is used to skip docker shutdown and docker remove.  We typically want to skip these for local development but not in the CI environment (where we want the docker container to be stopped and removed).

e.g.
```yaml
ebean:
#  dumpMetricsOnShutdown: true
#  dumpMetricsOptions: loc #hash,sql,loc
  test:
    localDevelopment: ~/.ebean/ignore-docker-shutdown  # ignore shutdown for local development
    shutdown: remove # stop | remove | none  
    platform: postgres
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: my_app

```
