### ISSUE TITLE
Refactor and rename into io.ebean.test : ebean-test-config ... as it is not just about docker

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-config#6]
Refer to https://github.com/ebean-orm/ebean/issues/1283

## Examples
Put settings into `src/test/resources/application-test.yml` like:

#### Basic H2  
```yml
ebean:
  test:
    platform: h2
```
This is all we need to run tests against H2 using defaults.

#### Basic Postgres   
```yml
ebean:
  test:
    platform: postgres
    dbName: test_myapp
```
