### ISSUE TITLE
ENH: Support ebean.test.shutdown ... as stop or remove ... to auto shutdown the container on JVM shutdown

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-config#8]
These use https://github.com/ebean-orm/ebean-test-docker/issues/21 ... to support automatically stop or stopping and removing the container on JVM shutdown.

**Example**: shutdown: stop ... to stop the container only on shutdown
```yml
ebean:
  test:
    shutdown: stop
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: test_ex
```

**Example**: shutdown: remove ... to stop and remove the container on shutdown.

```yml
ebean:
  test:
    shutdown: remove
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: test_ex
```
